---
title: PHPBees
timezone: Asia/Kolkata
collections:
  post-tags:
    title: Post Tags
    output: true
    layout: tag_page
  posts:
    title: Posts
    output: true
    comments: true
  uploads:
    title: Uploads
    output: true
author: Smit Shah
email: smitshah81@gmail.com
description: 'PHPBees is programming blog created from a programmer and dedicated
  to a programmer.Tutorial focused on PHP Programming,JavaScript and it''s framework.

'
twitter_username: smit_shah_
github_username: smitshah81
sass:
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll/tagging
gems:
- jekyll/tagging
permalink: ordinal
disqus:
  shortname: php-bees
google_analytics: UA-70275005-1
tag_page_layout: tag_page
tag_page_dir: post-tags
