---
title: PHPBees
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
    comments: true
  tags:
    title: Tags
    output: true
    permalink: "/tags"
  uploads:
    title: Uploads
    output: true
author: Smit Shah
email: smitshah81@gmail.com
description: 'PHPBees is programming blog created from a programmer and dedicated
  to a programmer.Tutorial focused on PHP Programming,JavaScript and it''s framework.

'
twitter_username: smit_shah_
github_username: smitshah81
sass:
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll/tagging
- jekyll-paginate
- jekyll-optional-front-matter
disqus:
  shortname: php-bees
google_analytics: UA-70275005-1
tag_page_layout: tag_page
tag_page_dir: "tags"
plugins_dir: _plugins
