---
title: Starter Template
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Panoramedia
email: panoramedia@gmail.com
description: 'A Site Starter Materialize Templates for Jekyll

'
twitter_username: macrod68
github_username: macrod68
sass:
  style: compressed
